'use client';
import { useState } from 'react';
import Sidebar from '@/components/Sidebar';
import { Phone, MessageCircle, UploadCloud, ArrowRight } from 'lucide-react';
import { telephony } from '@/lib/telephonyService';

export default function OperacaoPage() {
  const [lead,setLead]=useState<any>({id:'123e4567-e89b-12d3-a456-426614174000',nome:'Maria Silva Santos',cpf:'123.456.789-00',telefone:'79999999999',margem_disponivel:'450.00'});
  const [status,setStatus]=useState('FINALIZADO'); const [audio,setAudio]=useState<File|null>(null); const [loading,setLoading]=useState(false);
  async function finalizar(){setLoading(true);const fd=new FormData();fd.append('lead_id',lead.id);fd.append('status',status);if(audio)fd.append('file',audio);try{const r=await fetch('/api/call/complete',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha');setLead(d.proximoLead||null);setAudio(null);}catch(e){alert(e instanceof Error?e.message:'Falha');}finally{setLoading(false)}}
  return <div className="flex bg-slate-950 text-slate-100 min-h-screen"><Sidebar userRole="DONO"/><main className="flex-1 p-8"><div className="max-w-5xl mx-auto bg-slate-900 border border-slate-800 rounded-2xl p-6"><h1 className="text-xl font-bold text-indigo-400">Fila Inteligente &amp; Discador Mobile</h1><p className="text-xs text-slate-400 mt-1">Celular/Phone Link, WhatsApp e Auditoria IA.</p>{lead?<div className="mt-6 space-y-5"><div><h2 className="text-2xl font-bold">{lead.nome}</h2><p className="text-xs text-slate-400">CPF {lead.cpf} • +{telephony.formatPhoneNumber(lead.telefone)}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>telephony.openWhatsApp(lead.telefone,`Olá ${lead.nome}, sou da equipe de crédito consignado da A&K. Podemos fazer uma simulação?`)} className="bg-emerald-600 text-white text-xs px-4 py-2.5 rounded-xl flex gap-2"><MessageCircle className="w-4 h-4"/> WhatsApp</button><button onClick={()=>telephony.makeCall(lead.telefone)} className="bg-indigo-600 text-white text-xs px-5 py-2.5 rounded-xl flex gap-2"><Phone className="w-4 h-4"/> Discar no Celular</button></div><div className="grid md:grid-cols-2 gap-3"><div className="bg-slate-800 p-4 rounded-xl"><span className="text-xs text-slate-400">Margem estimada</span><p className="text-xl font-bold text-indigo-400">R$ {lead.margem_disponivel}</p></div><label className="bg-slate-800 p-4 rounded-xl text-xs cursor-pointer"><UploadCloud className="inline w-4 h-4 mr-2"/>{audio?audio.name:'Anexar gravação'}<input type="file" accept=".mp3,.m4a,.wav,audio/*" className="hidden" onChange={e=>setAudio(e.target.files?.[0]||null)}/></label></div><div className="flex gap-3"><select value={status} onChange={e=>setStatus(e.target.value)} className="bg-slate-800 border border-slate-700 rounded-xl px-4 py-2 flex-1"><option value="FINALIZADO">Interessado / Proposta</option><option value="LIGAR_DEPOIS">Ligar Depois</option><option value="NPO">Não Perturbe</option><option value="SEM_INTERESSE">Sem Interesse</option></select><button disabled={loading} onClick={finalizar} className="bg-indigo-600 text-white px-5 rounded-xl flex gap-2">{loading?'Processando...':'Salvar e Próximo'}<ArrowRight className="w-4"/></button></div></div>:<p className="mt-8 text-slate-400">Nenhum lead disponível.</p>}</div></main></div>;
}
