"use client";
import { AIProviders } from "@/lib/ai-providers-global";

import {useEffect,useMemo,useRef,useState,type ReactNode} from "react";
import {createClient} from "@/lib/supabase/client";

const nav=["Dashboard","Inbox","Radar","Kanban","Clientes","Follow-ups","Ligações","Campanhas","Automações","Respostas rápidas","Equipe","Auditoria","IA","Provedores de IA","Configurações"];
const products=["INSS","Público","Privado","Cartão consignado","Cartão benefício","Crédito pessoal","Seguro médico","Seguro residencial","Seguro funeral","Energia solar","FGTS","Crédito do Trabalhador/CLT","SIAPE","Militar"];
const stages=["Novo","Contato","Proposta","Negociação","Fechado","Perdido"];

export default function Deskcomm({userId}:{userId:string}){
 const[v,setV]=useState("Dashboard"),[q,setQ]=useState(""),[dark,setDark]=useState(false),[role,setRole]=useState("operator");
 const[d,setD]=useState<any>({leads:[],conversations:[],followups:[],calls:[]}),[toast,setToast]=useState(""),[sel,setSel]=useState(""),[msgs,setMsgs]=useState<any[]>([]);
 const[busy,setBusy]=useState(false),[importing,setImporting]=useState(false),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState("");
 const file=useRef<HTMLInputElement>(null);
 const load=async()=>{setLoading(true);setLoadError("");try{const r=await fetch("/api/crm?resource=dashboard",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Falha ao carregar");setD(j);setRole(j.role||"operator")}catch(e){setLoadError(e instanceof Error?e.message:"Falha ao carregar")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),3500);return()=>clearTimeout(t)},[toast]);
 const post=async(resource:string,data:any)=>{setBusy(true);try{const r=await fetch("/api/crm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource,data})});const j=await r.json().catch(()=>({}));if(!r.ok){setToast(j.error||"Operação recusada");return false}setToast("Operação concluída");await load();return true}finally{setBusy(false)}};
 const get=async(resource:string)=>{const r=await fetch("/api/crm?resource="+encodeURIComponent(resource),{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Falha ao carregar");return j};
 const select=async(id:string)=>{setSel(id);const r=await fetch("/api/crm?resource=messages&conversation_id="+encodeURIComponent(id));if(r.ok)setMsgs((await r.json()).messages||[])};
 const active=d.conversations.find((x:any)=>x.id===sel)||d.conversations[0];
 const filtered=useMemo(()=>d.leads.filter((x:any)=>((x.contact?.name||"")+" "+(x.contact?.phone||"")+" "+(x.product||"")).toLowerCase().includes(q.toLowerCase())),[d.leads,q]);
 const imp=async()=>{const fs=Array.from(file.current?.files||[]);if(!fs.length)return;setImporting(true);try{const fd=new FormData();fs.forEach(f=>fd.append("files",f));const r=await fetch("/api/import",{method:"POST",body:fd});const j=await r.json();setToast(r.ok?"Importados "+j.imported+" leads em "+(j.files?.length||fs.length)+" arquivo(s)":j.error||"Falha na importação");if(r.ok)await load()}finally{setImporting(false);if(file.current)file.current.value=""}}
 const logout=async()=>{await createClient().auth.signOut();location.href="/login"};
 return <div className={dark?"app dark":"app"}>
  <aside><div className="brand">A&K <em>Deskcomm</em></div><div className="org">SOLUÇÕES FINANCEIRAS</div>{nav.map(x=><button key={x} className={v===x?"nav active":"nav"} onClick={()=>setV(x)}><b>{icon(x)}</b>{x}</button>)}<div className="asideBottom"><button className="theme" onClick={()=>setDark(!dark)}>◐ Tema</button><button className="theme" onClick={logout}>↪ Sair</button></div></aside>
  <main><header><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar cliente, telefone ou produto..."/><span className="online">● Operação protegida</span><div className="avatar">AK</div><div><b>{role==="owner"||role==="admin"?"Administrador":role==="manager"?"Gerente":"Operador"}</b><small>{userId.slice(0,8)}…</small></div></header>
   <section>{loading&&<div className="loadingBar">Carregando dados reais…</div>}{loadError&&<div className="notice errorNotice">Erro: {loadError} <button className="btn" onClick={load}>Tentar novamente</button></div>}
    {v==="Dashboard"&&<Dashboard d={d} go={setV}/>}
    {v==="Inbox"&&<Inbox d={d} active={active} sel={sel} select={select} msgs={msgs} setMsgs={setMsgs} post={post} get={get} busy={busy}/>}
    {v==="Radar"&&<Radar filtered={filtered} post={post}/>}
    {v==="Kanban"&&<Kanban filtered={filtered} post={post} open={()=>setV("Clientes")}/>}
    {v==="Clientes"&&<Clientes filtered={filtered} importFile={()=>file.current?.click()} importing={importing} post={post} get={get}/>}
    {v==="Follow-ups"&&<Followups d={d} post={post}/>}
    {v==="Ligações"&&<Calls d={d} post={post}/>}
    {v==="Campanhas"&&<Campaigns post={post} get={get}/>}
    {v==="Automações"&&<Automations post={post} get={get}/>}
    {v==="Respostas rápidas"&&<QuickReplies post={post} get={get}/>}
    {v==="Equipe"&&<Module resource="team" title="Equipe" sub="Membros reais da organização" get={get}/>}
    {v==="Auditoria"&&<Module resource="audit" title="Auditoria" sub="Trilha real de operações" get={get}/>}
    {v==="IA"&&<AI post={post} get={get}/>}\n    {v==="Provedores de IA"&&<AIProviders/>}
    {v==="Configurações"&&<Settings role={role}/>}
   </section>
  </main>
  <input ref={file} hidden multiple type="file" accept=".csv,.xls,.xlsx,.ods" onChange={imp}/>
  {toast&&<div className="toast" onClick={()=>setToast("")}>✓ {toast}</div>}
 </div>
}

function icon(x:string){return x==="Dashboard"?"⌂":x==="Inbox"?"◉":x==="Ligações"?"☎":x==="Clientes"?"♙":x==="Kanban"?"▦":"•"}
function Head({title,sub,action}:{title:string;sub:string;action?:ReactNode}){return <div className="title"><div><h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function Metric({a,b,c}:{a:string;b:string;c:string}){return <div className="card metric"><small>{a}</small><strong>{b}</strong><span>{c}</span></div>}
function List({title,rows}:{title:string;rows:string[]}){return <div className="card"><h3>{title}</h3>{rows.length?rows.map((x,i)=><div className="row" key={i}>{x}</div>):<div className="empty">Nenhum registro.</div>}</div>}

function Dashboard({d,go}:{d:any;go:(x:string)=>void}){return <><Head title="Visão geral" sub="Dados reais do Supabase" action={<button className="btn primary" onClick={()=>go("Clientes")}>Gerenciar clientes</button>}/><div className="metrics"><Metric a="Leads ativos" b={String(d.leads.filter((x:any)=>!x.contact?.blocked).length)} c="Banco real"/><Metric a="Conversas" b={String(d.conversations.length)} c="Fila"/><Metric a="Follow-ups" b={String(d.followups.length)} c="Pendentes"/><Metric a="Ligações" b={String(d.calls.length)} c="Histórico"/></div><div className="cols"><List title="Pipeline" rows={d.leads.slice(0,10).map((x:any)=>x.contact?.name+" · "+x.product+" · "+x.stage)}/><div className="card"><h3>Operação</h3><div className="row">Supabase + RLS <span className="pill green">Ativo</span></div><div className="row">Importação múltipla <span className="pill green">Ativo</span></div><div className="row">Auditoria <span className="pill green">Ativo</span></div><div className="row">Phone Link <span className="pill">Somente discadora</span></div></div></div></>}

function Inbox({d,active,sel,select,msgs,setMsgs,post,get,busy}:{d:any;active:any;sel:string;select:(x:string)=>void;msgs:any[];setMsgs:(x:any[])=>void;post:(r:string,x:any)=>Promise<boolean>;get:(r:string)=>Promise<any>;busy:boolean}){
 const[text,setText]=useState("");const[show,setShow]=useState(false);const[contacts,setContacts]=useState<any[]>([]);
 return <><Head title="Inbox" sub="Conversas e mensagens reais" action={<button className="btn primary" onClick={async()=>{const j=await get("contacts");setContacts(j.contacts||[]);setShow(true)}}>+ Nova conversa</button>}/><div className="inbox"><div className="list">{d.conversations.map((c:any)=><button className={sel===c.id?"conv active":"conv"} key={c.id} onClick={()=>select(c.id)}><b>{c.contact?.name}</b><small>{c.channel} · {c.status}</small></button>)}{!d.conversations.length&&<div className="empty">Nenhuma conversa. Crie a primeira.</div>}</div><div className="chat">{active?<><div className="chathead"><b>{active.contact?.name}</b><small>{active.channel} · {active.contact?.phone}</small></div><div className="messages">{msgs.map(m=><div className={"bubble "+(m.direction==="outbound"?"agent":"")} key={m.id}>{m.body}<small>{new Date(m.created_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</small></div>)}</div><div className="composer"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Registrar mensagem…"/><button disabled={busy||!text.trim()} className="btn primary" onClick={async()=>{if(await post("message",{conversation_id:active.id,text:text.trim()})){setText("");const r=await fetch("/api/crm?resource=messages&conversation_id="+active.id);if(r.ok)setMsgs((await r.json()).messages||[])}}}>Registrar</button></div></>:<div className="empty">Selecione uma conversa.</div>}</div><div className="detail"><h3>Customer 360</h3>{active?<><div className="bigavatar">{active.contact?.name?.slice(0,2)}</div><b>{active.contact?.name}</b><small>{active.contact?.phone}</small><hr/><span className="tag">{active.channel}</span><span className="tag">{active.status}</span></>:<small>Nenhum contato.</small>}</div></div>{show&&<ContactPicker contacts={contacts} close={()=>setShow(false)} save={async(x)=>{if(await post("conversation",x))setShow(false)}}/>}</>
}

function ContactPicker({contacts,close,save}:{contacts:any[];close:()=>void;save:(x:any)=>void}){const[id,setId]=useState(contacts[0]?.id||"");const[channel,setChannel]=useState("internal");return <div className="modal"><form className="modalbox" onSubmit={e=>{e.preventDefault();save({contact_id:id,channel})}}><div className="title"><h2>Nova conversa</h2><button type="button" className="btn" onClick={close}>Fechar</button></div><label>Cliente<select value={id} onChange={e=>setId(e.target.value)}>{contacts.map(c=><option key={c.id} value={c.id}>{c.name} · {c.phone}</option>)}</select></label><label>Canal<select value={channel} onChange={e=>setChannel(e.target.value)}><option value="internal">Interno</option><option value="whatsapp">WhatsApp</option><option value="instagram">Instagram</option><option value="web">Web</option></select></label><button className="btn primary wide" disabled={!id}>Abrir conversa</button></form></div>}

function Radar({filtered,post}:{filtered:any[];post:(r:string,x:any)=>Promise<boolean>}){return <><Head title="Radar" sub="Bloqueios e prioridades"/><div className="card">{filtered.map(x=><div className="row" key={x.id}><div><b>{x.contact?.name}</b><small>{x.contact?.phone} · {x.product}</small></div>{x.contact?.blocked||x.contact?.npd?<span className="pill red">{x.contact?.blocked_reason||"NPD"}</span>:<button className="btn" onClick={()=>post("block",{phone:x.contact?.phone,reason:"nao_ligar"})}>Não ligar</button>}</div>)}{!filtered.length&&<div className="empty">Nenhum cliente encontrado.</div>}</div></>}

function Kanban({filtered,post,open}:{filtered:any[];post:(r:string,x:any)=>Promise<boolean>;open:()=>void}){return <><Head title="Kanban" sub="Pipeline comercial" action={<button className="btn primary" onClick={open}>+ Novo lead</button>}/><div className="kanban">{stages.map(s=><div className="column" key={s}><h3>{s}<span>{filtered.filter(x=>x.stage===s).length}</span></h3>{filtered.filter(x=>x.stage===s).map(x=><div className="lead" key={x.id}><b>{x.contact?.name}</b><small>{x.contact?.phone}</small><span className="tag">{x.product}</span><select value={x.stage} onChange={e=>post("lead_update",{id:x.id,stage:e.target.value})}>{stages.map(y=><option key={y}>{y}</option>)}</select></div>)}</div>)}</div></>}

function Clientes({filtered,importFile,importing,post,get}:{filtered:any[];importFile:()=>void;importing:boolean;post:(r:string,x:any)=>Promise<boolean>;get:(r:string)=>Promise<any>}){const[show,setShow]=useState(false);const[imports,setImports]=useState<any[]>([]);const loadImports=async()=>{const j=await get("import_jobs");setImports(j.importJobs||[])};useEffect(()=>{loadImports()},[]);return <><Head title="Clientes" sub="Base comercial persistida" action={<><button className="btn" onClick={importFile}>{importing?"Importando…":"Importar 1 ou várias planilhas"}</button><button className="btn primary" onClick={()=>setShow(true)}>+ Novo cliente</button></>}/><div className="card"><div className="notice">Você pode selecionar várias planilhas simultaneamente. CSV, XLS, XLSX e ODS. O CRM consolida tudo e evita duplicação pelo telefone.</div><div className="tablewrap"><table><thead><tr><th>Cliente</th><th>Telefone</th><th>Produto</th><th>Etapa</th><th>Status</th><th>Ação</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td>{x.contact?.name}</td><td>{x.contact?.phone}</td><td>{x.product}</td><td><span className="pill">{x.stage}</span></td><td><span className={x.contact?.blocked?"pill red":"pill green"}>{x.contact?.blocked?"Bloqueado":"Ativo"}</span></td><td><button className="btn" onClick={()=>post("block",{phone:x.contact?.phone,reason:"nao_ligar"})}>Bloquear</button></td></tr>)}</tbody></table></div></div><div className="card"><h3>Histórico de importações</h3>{imports.map(x=><div className="row" key={x.id}><span>{x.file_name}</span><span>{x.row_count} · {x.status}</span></div>)}{!imports.length&&<div className="empty">Nenhuma importação registrada.</div>}</div>{show&&<LeadModal title="Novo cliente/lead" close={()=>setShow(false)} save={async x=>{if(await post("lead",x))setShow(false)}}/>}</>}

function LeadModal({title,close,save}:{title:string;close:()=>void;save:(x:any)=>void}){const[n,setN]=useState(""),[p,setP]=useState(""),[prod,setProd]=useState(products[0]);return <div className="modal"><form className="modalbox" onSubmit={e=>{e.preventDefault();save({name:n,phone:p,product:prod})}}><div className="title"><h2>{title}</h2><button type="button" className="btn" onClick={close}>Fechar</button></div><label>Nome<input value={n} onChange={e=>setN(e.target.value)} required/></label><label>Telefone<input value={p} onChange={e=>setP(e.target.value)} required/></label><label>Produto<select value={prod} onChange={e=>setProd(e.target.value)}>{products.map(x=><option key={x}>{x}</option>)}</select></label><button className="btn primary wide">Salvar</button></form></div>}

function Followups({d,post}:{d:any;post:(r:string,x:any)=>Promise<boolean>}){const[show,setShow]=useState(false);return <><Head title="Follow-ups" sub="Retornos e tarefas reais" action={<button className="btn primary" onClick={()=>setShow(true)}>+ Novo follow-up</button>}/><div className="card">{d.followups.map((x:any)=><div className="row" key={x.id}><div><b>{x.title}</b><small>{new Date(x.due_at).toLocaleString("pt-BR")} · {x.lead_id||""}</small></div><button className="btn" onClick={()=>post("followup_update",{id:x.id,status:"done"})}>Concluir</button></div>)}{!d.followups.length&&<div className="empty">Nenhum follow-up pendente.</div>}</div>{show&&<FollowupModal leads={d.leads} close={()=>setShow(false)} save={async x=>{if(await post("followup",x))setShow(false)}}/>}</>}

function FollowupModal({leads,close,save}:{leads:any[];close:()=>void;save:(x:any)=>void}){const[lead,setLead]=useState(leads[0]?.id||""),[title,setTitle]=useState("Retorno comercial"),[due,setDue]=useState("");return <div className="modal"><form className="modalbox" onSubmit={e=>{e.preventDefault();save({lead_id:lead,title,due_at:new Date(due).toISOString()})}}><div className="title"><h2>Novo follow-up</h2><button type="button" className="btn" onClick={close}>Fechar</button></div><label>Lead<select value={lead} onChange={e=>setLead(e.target.value)}>{leads.map(x=><option key={x.id} value={x.id}>{x.contact?.name} · {x.product}</option>)}</select></label><label>Título<input value={title} onChange={e=>setTitle(e.target.value)} required/></label><label>Data/hora<input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)} required/></label><button className="btn primary wide">Salvar</button></form></div>}

function Calls({d,post}:{d:any;post:(r:string,x:any)=>Promise<boolean>}){const[show,setShow]=useState(false);return <><Head title="Ligações" sub="Histórico do CRM; discagem continua na ak-call-center" action={<button className="btn primary" onClick={()=>setShow(true)}>+ Registrar ligação</button>}/><div className="card">{d.calls.map((x:any)=><div className="row" key={x.id}><div><b>{x.phone}</b><small>{x.result} · {x.duration_seconds}s · {new Date(x.created_at).toLocaleString("pt-BR")}</small></div></div>)}{!d.calls.length&&<div className="empty">Nenhuma ligação registrada.</div>}</div>{show&&<CallModal leads={d.leads} close={()=>setShow(false)} save={async x=>{if(await post("call",x))setShow(false)}}/>}</>}

function CallModal({leads,close,save}:{leads:any[];close:()=>void;save:(x:any)=>void}){const[lead,setLead]=useState(leads[0]?.id||""),[result,setResult]=useState("Atendeu"),[dur,setDur]=useState("60");const current=leads.find(x=>x.id===lead);return <div className="modal"><form className="modalbox" onSubmit={e=>{e.preventDefault();save({lead_id:lead||null,phone:current?.contact?.phone||"",result,duration_seconds:Number(dur)})}}><div className="title"><h2>Registrar ligação</h2><button type="button" className="btn" onClick={close}>Fechar</button></div><label>Lead<select value={lead} onChange={e=>setLead(e.target.value)}>{leads.map(x=><option key={x.id} value={x.id}>{x.contact?.name} · {x.contact?.phone}</option>)}</select></label><label>Resultado<select value={result} onChange={e=>setResult(e.target.value)}>{["Atendeu","Não atendeu","Retornar","Ocupado","Número inválido"].map(x=><option key={x}>{x}</option>)}</select></label><label>Duração (segundos)<input type="number" min="0" value={dur} onChange={e=>setDur(e.target.value)}/></label><button className="btn primary wide">Salvar</button></form></div>}

function Campaigns({post,get}:{post:(r:string,x:any)=>Promise<boolean>;get:(r:string)=>Promise<any>}){const[data,setData]=useState<any[]>([]),[show,setShow]=useState(false),[name,setName]=useState(""),[product,setProduct]=useState(products[0]);const load=()=>get("campaigns").then(j=>setData(j.campaigns||[]));useEffect(()=>{load()},[]);return <><Head title="Campanhas" sub="Criação e status persistidos" action={<button className="btn primary" onClick={()=>setShow(true)}>+ Nova campanha</button>}/>{show&&<div className="card"><label>Nome<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Produto<select value={product} onChange={e=>setProduct(e.target.value)}>{products.map(x=><option key={x}>{x}</option>)}</select></label><button className="btn primary" onClick={async()=>{if(await post("campaign",{name,product})){setShow(false);setName("");load()}}}>Salvar</button></div>}<div className="card">{data.map(x=><div className="row" key={x.id}><div><b>{x.name}</b><small>{x.product||"Sem produto"}</small></div><select value={x.status} onChange={async e=>{if(await post("campaign_update",{id:x.id,status:e.target.value}))load()}}><option>draft</option><option>active</option><option>paused</option><option>finished</option></select></div>)}{!data.length&&<div className="empty">Nenhuma campanha.</div>}</div></>}

function Automations({post,get}:{post:(r:string,x:any)=>Promise<boolean>;get:(r:string)=>Promise<any>}){const[data,setData]=useState<any[]>([]),[show,setShow]=useState(false),[name,setName]=useState(""),[action,setAction]=useState("");const load=()=>get("automations").then(j=>setData(j.automations||[]));useEffect(()=>{load()},[]);return <><Head title="Automações" sub="Regras que podem ser ativadas/desativadas" action={<button className="btn primary" onClick={()=>setShow(true)}>+ Nova automação</button>}/>{show&&<div className="card"><label>Nome<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Ação<input value={action} onChange={e=>setAction(e.target.value)} placeholder="Criar follow-up"/></label><button className="btn primary" onClick={async()=>{if(await post("automation",{name,trigger:"manual",action})){setShow(false);setName("");setAction("");load()}}}>Salvar</button></div>}<div className="card">{data.map(x=><div className="row" key={x.id}><div><b>{x.name}</b><small>{x.trigger_name} → {x.action_name}</small></div><button className="btn" onClick={async()=>{if(await post("automation_toggle",{id:x.id,enabled:!x.enabled}))load()}}>{x.enabled?"Desativar":"Ativar"}</button></div>)}{!data.length&&<div className="empty">Nenhuma automação.</div>}</div></>}

function QuickReplies({post,get}:{post:(r:string,x:any)=>Promise<boolean>;get:(r:string)=>Promise<any>}){const[data,setData]=useState<any[]>([]),[name,setName]=useState(""),[body,setBody]=useState("");const load=()=>get("quick_replies").then(j=>setData(j.quickReplies||[]));useEffect(()=>{load()},[]);return <><Head title="Respostas rápidas" sub="Biblioteca operacional persistida" /><div className="card"><div className="row"><input placeholder="Nome" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Mensagem" value={body} onChange={e=>setBody(e.target.value)}/><button className="btn primary" onClick={async()=>{if(await post("quick_reply",{name,body})){setName("");setBody("");load()}}}>Adicionar</button></div></div><div className="card">{data.map(x=><div className="row" key={x.id}><b>{x.name}</b><span>{x.body}</span></div>)}{!data.length&&<div className="empty">Nenhuma resposta rápida.</div>}</div></>}

function Module({resource,title,sub,get}:{resource:string;title:string;sub:string;get:(r:string)=>Promise<any>}){const[r,setR]=useState<any[]>([]),[err,setErr]=useState("");useEffect(()=>{get(resource).then(j=>setR(j[resource]||j.team||j.audit||[])).catch(e=>setErr(e.message))},[resource]);return <><Head title={title} sub={sub}/><div className="card">{err&&<div className="notice errorNotice">{err}</div>}{r.map((x:any,i)=><div className="row" key={x.id||i}><div><b>{x.name||x.action||x.action_name||x.resource_type||"Registro"}</b><small>{x.user_id||x.actor_id||x.resource_id||""}</small></div><span className="pill">{x.role||x.outcome||x.status||""}</span></div>)}{!r.length&&!err&&<div className="empty">Nenhum registro.</div>}</div></>}

function AI({post,get}:{post:(r:string,x:any)=>Promise<boolean>;get:(r:string)=>Promise<any>}){
 const[agents,setAgents]=useState<any[]>([]),[skills,setSkills]=useState<any[]>([]),[show,setShow]=useState(false);
 const[name,setName]=useState(""),[model,setModel]=useState("openai/gpt-5.6-luna"),[skill,setSkill]=useState("");
 const[prompt,setPrompt]=useState(""),[answer,setAnswer]=useState(""),[aiBusy,setAiBusy]=useState(false),[aiError,setAiError]=useState("");
 const load=async()=>{const[a,s]=await Promise.all([get("ai_agents"),get("ai_skills")]);setAgents(a.agents||[]);setSkills(s.skills||[])};
 useEffect(()=>{load()},[]);
 const models=[
  ["openai/gpt-5.6-luna","GPT-5.6 Luna","baixo","Atendimento e alto volume"],
  ["openai/gpt-5.6-terra","GPT-5.6 Terra","médio","Análise e operação comercial"],
  ["openai/gpt-5.6-sol","GPT-5.6 Sol","alto","Agentes e tarefas complexas"],
  ["anthropic/claude-sonnet-4.6","Claude Sonnet 4.6","pago","Alternativa Anthropic"],
  ["google/gemini-2.5-flash","Gemini 2.5 Flash","pago","Alternativa Google"]
 ];
 const run=async()=>{if(!prompt.trim())return;setAiBusy(true);setAiError("");setAnswer("");try{const r=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model,prompt})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Falha na IA");setAnswer(j.text||"");}catch(e){setAiError(e instanceof Error?e.message:"Falha na IA")}finally{setAiBusy(false)}};
 return <><Head title="IA / Agentes / Provedores" sub="Agentes, skills e execução real via AI Gateway" action={<button className="btn primary" onClick={()=>setShow(true)}>+ Novo agente</button>}/>
 <div className="cols">
  <div className="card">
   <h3>Provedores e modelos</h3>
   <p className="muted">O catálogo fica no CRM. A execução usa AI Gateway, sem expor chaves no navegador.</p>
   {models.map(([id,label,cost,desc])=><button key={id} className={model===id?"modelChoice active":"modelChoice"} onClick={()=>setModel(id)}><span><b>{label}</b><small>{desc}</small></span><span className="pill">{cost}</span></button>)}
   <div className="notice">Modo econômico: GPT-5.6 Luna. O AI Gateway oferece créditos promocionais para usuários gratuitos; depois disso, o uso segue o preço do provedor/modelo.</div>
  </div>
  <div className="card">
   <h3>Teste operacional da IA</h3>
   <label>Modelo ativo<select value={model} onChange={e=>setModel(e.target.value)}>{models.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
   <label>Prompt<textarea className="aiPrompt" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ex.: crie uma abordagem inicial para um cliente interessado em cartão benefício." maxLength={12000}/></label>
   <button className="btn primary" disabled={aiBusy||!prompt.trim()} onClick={run}>{aiBusy?"Consultando IA…":"Testar IA agora"}</button>
   {aiError&&<div className="notice errorNotice">{aiError}</div>}
   {answer&&<div className="aiAnswer"><b>Resposta</b><p>{answer}</p></div>}
  </div>
 </div>
 {show&&<div className="card"><label>Nome do agente<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: A&K Comercial"/></label><label>Modelo<select value={model} onChange={e=>setModel(e.target.value)}>{models.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><button className="btn primary" onClick={async()=>{const ok=await createAgent(post,{name,model});if(ok){setShow(false);setName("");load()}}}>Salvar agente</button></div>}
 <div className="cols">
  <div className="card"><h3>Agentes</h3>{agents.map(x=><div className="row" key={x.id}><div><b>{x.name}</b><small>{x.provider||"AI Gateway"} · {x.model||"Modelo não definido"}</small></div><span className={x.enabled?"pill green":"pill"}>{x.enabled?"Ativo":"Desativado"}</span></div>)}{!agents.length&&<div className="empty">Nenhum agente cadastrado.</div>}</div>
  <div className="card"><h3>Skills</h3>{skills.map(x=><div className="row" key={x.id}><span>{x.name}</span><span className={x.enabled?"pill green":"pill"}>{x.enabled?"Ativa":"Desativada"}</span></div>)}{!skills.length&&<div className="empty">Nenhuma skill cadastrada.</div>}<div className="row"><input value={skill} onChange={e=>setSkill(e.target.value)} placeholder="Nome da skill"/><button className="btn" onClick={async()=>{if(skill.trim()&&await post("ai_skill",{name:skill.trim()})){setSkill("");load()}}}>Cadastrar</button></div></div>
 </div></>
}

async function createAgent(post:(r:string,x:any)=>Promise<boolean>,data:any){return post("ai_agent",data)}

function Settings({role}:{role:string}){return <><Head title="Configurações" sub="Ambiente conectado"/><div className="cols"><div className="card"><h3>Segurança</h3><div className="row">Sessão SSR <span className="pill green">Ativa</span></div><div className="row">RLS multi-tenant <span className="pill green">Ativo</span></div><div className="row">Permissão atual <span className="pill">{role}</span></div><div className="row">API cache <span className="pill green">Privado</span></div></div><div className="card"><h3>Integração</h3><p>Deskcomm registra CRM. A discagem/Phone Link continua exclusivamente no projeto ak-call-center.</p><p>O próximo conector poderá trocar eventos autenticados entre os dois projetos sem mover o Phone Link.</p></div></div></>}

